import { describe, expect, it } from 'vitest';
import {
  checkQuality,
  countQuestions,
  emojiCount,
  filterSuggestions,
  hashtagCount,
  postOverlapRatio,
  similarity,
  wordCount,
} from '../ai/quality.js';

const base = {
  length: 'medium' as const,
  emojiPreference: 'none' as const,
  allowHashtags: false,
  maxQuestionModeTone: 'none' as const,
};

describe('wordCount / emojiCount / hashtagCount', () => {
  it('counts words', () => {
    expect(wordCount('one two three')).toBe(3);
    expect(wordCount('')).toBe(0);
  });
  it('counts emojis', () => {
    expect(emojiCount('nice 👏 work')).toBe(1);
    expect(emojiCount('nothing here')).toBe(0);
  });
  it('counts hashtags', () => {
    expect(hashtagCount('check #product and #ai')).toEqual(['#product', '#ai']);
  });
  it('counts questions', () => {
    expect(countQuestions('Is this right? And this?')).toBe(2);
  });
});

describe('generic openers', () => {
  const generic = [
    'Great post, thanks for sharing this!',
    'Thanks for sharing your thoughts here.',
    'This is so insightful, absolutely agree.',
    'Great post!',
    'Love this!',
  ];
  for (const text of generic) {
    it(`rejects "${text.slice(0, 24)}..."`, () => {
      expect(checkQuality(text, base).rejected).toBe(true);
    });
  }
});

describe('AI self-reference', () => {
  it('rejects comments mentioning AI generation', () => {
    expect(checkQuality('As an AI, I found this post interesting.', base).rejected).toBe(true);
    expect(checkQuality('This comment was generated by an AI assistant.', base).rejected).toBe(true);
  });
});

describe('unsupported statistics', () => {
  it('rejects fabricated statistics', () => {
    expect(checkQuality('This affects 87% of professionals.', base).rejected).toBe(true);
    expect(checkQuality('According to a recent study, most teams struggle.', base).rejected).toBe(true);
  });
});

describe('length bounds', () => {
  it('rejects comments far beyond the requested range', () => {
    const long = Array.from({ length: 90 }, (_, i) => `word${i}`).join(' ');
    expect(checkQuality(long, { ...base, length: 'short' }).rejected).toBe(true);
  });
  it('accepts a reasonable medium comment', () => {
    const ok =
      'This mirrors what I have seen on the product side, where honest feedback loops changed how quickly we shipped.';
    expect(checkQuality(ok, base).rejected).toBe(false);
  });
});

describe('emoji policy', () => {
  it('rejects emojis when preference is none', () => {
    expect(checkQuality('Nice work on this 👏', base).rejected).toBe(true);
  });
  it('allows a single emoji when occasional', () => {
    const result = checkQuality('Nice work on this 👏', {
      ...base,
      emojiPreference: 'occasional',
    });
    expect(result.rejected).toBe(false);
  });
  it('rejects multiple emojis when occasional', () => {
    expect(
      checkQuality('Nice work on this 👏🔥🎉', { ...base, emojiPreference: 'occasional' }).rejected,
    ).toBe(true);
  });
});

describe('hashtags', () => {
  it('rejects hashtags when not requested', () => {
    expect(checkQuality('Great analysis on #product strategy.', base).rejected).toBe(true);
  });
});

describe('question-led tone', () => {
  it('rejects more than one question in question-led mode', () => {
    const result = checkQuality('Why did you choose this? Was the rollout hard?', {
      ...base,
      maxQuestionModeTone: 'question_led',
    });
    expect(result.rejected).toBe(true);
  });
});

describe('similarity', () => {
  it('detects near-duplicate comments', () => {
    const a = 'The practical takeaway is that small teams ship faster with clear ownership.';
    const b = 'The practical takeaway is that small teams ship faster with clear ownership.';
    expect(similarity(a, b)).toBeGreaterThan(0.9);
  });
  it('keeps distinct comments distinct', () => {
    const a = 'Clear ownership helped our small team ship faster.';
    const b = 'Customer interviews were the reason we changed our pricing page completely.';
    expect(similarity(a, b)).toBeLessThan(0.5);
  });
});

describe('post overlap', () => {
  it('flags comments that repeat large chunks of the post', () => {
    const post = 'Our team spent a full year interviewing customers before we rebuilt the dashboard.';
    const comment =
      'Our team spent a full year interviewing customers before we rebuilt the dashboard, and it paid off.';
    expect(postOverlapRatio(comment, post)).toBeGreaterThan(0.6);
  });
});

describe('filterSuggestions', () => {
  const post = 'We shipped a new analytics dashboard after a year of customer interviews.';

  it('removes generic suggestions', () => {
    const filtered = filterSuggestions(
      [
        { tone: 'professional', text: 'Great post!' },
        { tone: 'insightful', text: 'The year of customer interviews is the real story here.' },
      ],
      post,
      base,
    );
    expect(filtered).toHaveLength(1);
  });

  it('removes near-duplicate suggestions', () => {
    const same = 'The customer interviews are what made this dashboard work, and that is a useful lesson.';
    const filtered = filterSuggestions(
      [
        { tone: 'insightful', text: same },
        { tone: 'casual', text: same },
        { tone: 'supportive', text: 'A genuinely different angle: the pricing model deserves its own post.' },
      ],
      post,
      base,
    );
    expect(filtered).toHaveLength(2);
  });

  it('keeps three meaningfully different suggestions', () => {
    const suggestions = [
      { tone: 'insightful', text: 'The customer interview loop is the hidden ingredient behind this launch.' },
      { tone: 'question_led', text: 'What metric told you the new dashboard was actually working for users?' },
      { tone: 'supportive', text: 'A year of interviews before building is discipline most teams skip.' },
    ];
    const filtered = filterSuggestions(suggestions, post, base);
    expect(filtered).toHaveLength(3);
  });
});
