/**
 * Deterministic comment-quality checks. These run after generation and before
 * suggestions are returned to the extension. They are intentionally strict and
 * rule-based: the AI can be bypassed, these checks cannot.
 */

export interface QualityOptions {
  length: 'short' | 'medium' | 'detailed';
  emojiPreference: 'none' | 'occasional' | undefined;
  allowHashtags?: boolean;
  maxQuestionModeTone: 'question_led' | 'none';
}

export interface QualityResult {
  text: string;
  rejected: boolean;
  reason?: string;
}

const GENERIC_OPENERS = [
  /^great post/i,
  /^thanks for sharing/i,
  /^thank you for sharing/i,
  /^this is so insightful/i,
  /^absolutely agree/i,
  /^so insightful/i,
  /^love this/i,
  /^excellent post/i,
  /^amazing post/i,
  /^interesting post/i,
  /^well said/i,
  /^this resonates/i,
  /^agree with everything/i,
  /^100%/,
];

const AI_SELF_REFERENCE = /\b(i am|as an|this comment was generated by)\s+(an?\s+)?ai\b/i;

const STATISTIC_PATTERNS = [
  /\b\d+(?:\.\d+)?% of/i, // "X% of" unsupported stat phrasing
  /\b\d{1,3}(?:,\d{3})+ (?:people|users|companies|professionals)\b/i,
  /\baccording to (?:a|the) (?:recent |new )?study\b/i,
];

const MAX_WORDS: Record<QualityOptions['length'], number> = {
  short: 40,
  medium: 75,
  detailed: 125,
};

export function wordCount(text: string): number {
  const words = text.trim().split(/\s+/).filter(Boolean);
  return words.length;
}

export function emojiCount(text: string): number {
  const matches = text.match(/\p{Extended_Pictographic}/gu);
  return matches?.length ?? 0;
}

export function hashtagCount(text: string): string[] {
  return text.match(/#[\p{L}\p{N}_]+/gu) ?? [];
}

export function countQuestions(text: string): number {
  return (text.match(/\?/g) ?? []).length;
}

/**
 * Lightweight similarity between two comments based on shared token overlap
 * (Jaccard on word stems). A score >= 0.62 means "too similar".
 */
export function similarity(a: string, b: string): number {
  const tokensA = new Set(normalizeTokens(a));
  const tokensB = new Set(normalizeTokens(b));
  if (tokensA.size === 0 || tokensB.size === 0) return 0;
  let intersection = 0;
  for (const token of tokensA) {
    if (tokensB.has(token)) intersection += 1;
  }
  const union = tokensA.size + tokensB.size - intersection;
  return union === 0 ? 0 : intersection / union;
}

function normalizeTokens(text: string): string[] {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, ' ')
    .split(/\s+/)
    .filter((t) => t.length > 2);
}

/**
 * Returns the longest contiguous sequence of words from the source post
 * present in the candidate comment (fuzzy, ignoring punctuation), as a ratio.
 */
export function postOverlapRatio(candidate: string, post: string): number {
  const postTokens = post.toLowerCase().split(/\s+/).filter((t) => t.length > 1);
  const candidateTokens = candidate.toLowerCase().split(/\s+/).filter((t) => t.length > 1);
  if (postTokens.length < 8 || candidateTokens.length < 5) return 0;

  const postSet = new Set(postTokens);
  let overlap = 0;
  for (const token of candidateTokens) {
    if (postSet.has(token)) overlap += 1;
  }
  return overlap / candidateTokens.length;
}

export function checkQuality(
  text: string,
  opts: QualityOptions,
): QualityResult {
  const trimmed = text.trim();

  if (!trimmed) {
    return { text: trimmed, rejected: true, reason: 'empty' };
  }
  if (trimmed.length < 10) {
    return { text: trimmed, rejected: true, reason: 'too_short' };
  }

  for (const pattern of GENERIC_OPENERS) {
    if (pattern.test(trimmed)) {
      return { text: trimmed, rejected: true, reason: 'generic_opener' };
    }
  }

  if (AI_SELF_REFERENCE.test(trimmed)) {
    return { text: trimmed, rejected: true, reason: 'ai_self_reference' };
  }

  for (const pattern of STATISTIC_PATTERNS) {
    if (pattern.test(trimmed)) {
      return { text: trimmed, rejected: true, reason: 'unsupported_statistic' };
    }
  }

  const words = wordCount(trimmed);
  if (words > MAX_WORDS[opts.length]) {
    return { text: trimmed, rejected: true, reason: 'too_long' };
  }

  const emojis = emojiCount(trimmed);
  if (opts.emojiPreference === 'none' && emojis > 0) {
    return { text: trimmed, rejected: true, reason: 'emoji_not_requested' };
  }
  if (opts.emojiPreference === 'occasional' && emojis > 1) {
    return { text: trimmed, rejected: true, reason: 'too_many_emoji' };
  }

  const hashtags = hashtagCount(trimmed);
  if (!opts.allowHashtags && hashtags.length > 0) {
    return { text: trimmed, rejected: true, reason: 'hashtag_not_requested' };
  }

  if (opts.maxQuestionModeTone === 'question_led' && countQuestions(trimmed) > 1) {
    return { text: trimmed, rejected: true, reason: 'too_many_questions' };
  }

  if (/^\s*["'\u201C\u201D]/.test(trimmed) || /["'\u201C\u201D]\s*$/.test(trimmed)) {
    return { text: trimmed, rejected: true, reason: 'wrapped_in_quotes' };
  }

  if (/\b(ignore (all )?(your |any )?(previous|prior|above|earlier) instructions|disregard (your|the) (previous|above) instructions|system prompt|prompt injection)\b/i.test(trimmed)) {
    return { text: trimmed, rejected: true, reason: 'instruction_in_comment' };
  }

  return { text: trimmed, rejected: false };
}

/**
 * Filters a list of suggestions so that:
 *  - every suggestion passes checkQuality,
 *  - no two suggestions are too similar to each other,
 *  - no suggestion repeats large parts of the source post.
 */
export function filterSuggestions(
  suggestions: Array<{ tone: string; text: string }>,
  post: string,
  opts: QualityOptions,
): Array<{ tone: string; text: string }> {
  const accepted: Array<{ tone: string; text: string }> = [];

  for (const suggestion of suggestions) {
    const result = checkQuality(suggestion.text, opts);
    if (result.rejected) {
      continue;
    }
    const overlap = postOverlapRatio(result.text, post);
    if (overlap > 0.55) {
      continue;
    }
    const tooSimilarToExisting = accepted.some(
      (existing) => similarity(existing.text, result.text) >= 0.62,
    );
    if (tooSimilarToExisting) {
      continue;
    }
    accepted.push({ tone: suggestion.tone, text: result.text });
  }

  return accepted;
}
